### PR TITLE
Fix: Go back to the first page when searching the task list

### LINKED ISSUE #63: Searching for tasks while on a different page then 1 fails
If you've been browsing through your tasks, and suddenly have an idea what you want to do, but you aren't on page 1. You get "stuck":

image

As you can see I'm on page 18 of 1. With no tasks, when I click on the << button, it does show the tasks again:

image

### PR DESCRIPTION
**Pull request by JoeyKanaly**
Fixes #63

### CODE REVIEW

File: src/components/common/Table.js [hunk 1]
```diff
@@ -56,13 +56,18 @@ export default function Table({
   useEffect(() => {
     // Reset to first page when filters are changed
     table.gotoPage(0);
-  }, [filterState, forceResetPage]);
+    // eslint-disable-next-line no-console
```
Comment (DMills94) [inline src/components/common/Table.js:59]: Think you forgot to remove this 👍

Comment (JoeyKanaly) [reply src/components/common/Table.js]: Oops thanks missed that and an unused prop

**Comment by chaiinchomp** [comment]
OMG I AM SORRY I MISSED THIS PR
